import type { WorkConfig } from "./model.ts";

export const works: WorkConfig[] = [
  {
    slug: "the-iliad",
    author: "homer",
    authorName: "Homer",
    title: "The Iliad",
    composedYear: -750,
    era: "archaic-greece",
    adapter: "pg-the-iliad",
    rawDir: "raw/pg/the-iliad",
    translator: "Samuel Butler",
    refScheme: { primary: "book.paragraph", aliases: [], lineation: null },
  },
  {
    slug: "the-frogs",
    author: "aristophanes",
    authorName: "Aristophanes",
    title: "The Frogs",
    composedYear: -405,
    era: "classical-greece",
    adapter: "pg-the-frogs",
    rawDir: "raw/pg/the-frogs",
    translator: "Benjamin Bickley Rogers",
    refScheme: { primary: "line", aliases: [], lineation: "translation" },
  },
  {
    slug: "the-divine-comedy",
    author: "dante-alighieri",
    authorName: "Dante Alighieri",
    title: "The Divine Comedy",
    composedYear: 1320,
    era: "medieval",
    adapter: "se-divine-comedy",
    rawDir: "raw/se/the-divine-comedy",
    translator: "Henry Wadsworth Longfellow",
    refScheme: { primary: "cantica.canto:line", aliases: [], lineation: "translation" },
  },
  {
    slug: "histories",
    author: "herodotus",
    authorName: "Herodotus",
    title: "Histories",
    composedYear: -430,
    era: "classical-greece",
    adapter: "se-prose",
    rawDir: "raw/se/histories",
    translator: "G. C. Macaulay",
    refScheme: { primary: "book.paragraph", aliases: [], lineation: null },
    expectDivisions: 10, // translator's preface + 9 books
  },
  {
    slug: "history-of-the-peloponnesian-war",
    author: "thucydides",
    authorName: "Thucydides",
    title: "History of the Peloponnesian War",
    composedYear: -400,
    era: "classical-greece",
    adapter: "se-prose",
    rawDir: "raw/se/history-of-the-peloponnesian-war",
    translator: "Richard Crawley",
    refScheme: { primary: "chapter.paragraph", aliases: [], lineation: null },
    skipFiles: ["plans.xhtml"], // battle-plan images: no image path in v1
    expectDivisions: 27, // dedication + 26 chapters
  },
  {
    slug: "meditations",
    author: "marcus-aurelius",
    authorName: "Marcus Aurelius",
    title: "Meditations",
    composedYear: 175,
    era: "imperial-rome",
    adapter: "se-prose",
    rawDir: "raw/se/meditations",
    translator: "George Long",
    refScheme: { primary: "book.paragraph", aliases: [], lineation: null },
    expectDivisions: 12,
  },
  {
    slug: "the-prince",
    author: "niccolo-machiavelli",
    authorName: "Niccolò Machiavelli",
    title: "The Prince",
    composedYear: 1513,
    era: "renaissance",
    adapter: "se-prose",
    rawDir: "raw/se/the-prince",
    translator: "W. K. Marriott",
    refScheme: { primary: "chapter.paragraph", aliases: [], lineation: null },
    expectDivisions: 29, // intro, biography, dedication, 26 chapters
  },
  {
    slug: "leviathan",
    author: "thomas-hobbes",
    authorName: "Thomas Hobbes",
    title: "Leviathan",
    composedYear: 1651,
    era: "early-modern",
    adapter: "se-prose",
    rawDir: "raw/se/leviathan",
    translator: null,
    refScheme: { primary: "chapter.paragraph", aliases: [], lineation: null },
    expectDivisions: 50, // dedication, introduction, 47 chapters, conclusion
  },
  {
    slug: "moby-dick",
    author: "herman-melville",
    authorName: "Herman Melville",
    title: "Moby-Dick",
    composedYear: 1851,
    era: "nineteenth-century",
    adapter: "se-prose",
    rawDir: "raw/se/moby-dick",
    translator: null,
    refScheme: { primary: "chapter.paragraph", aliases: [], lineation: null },
    expectDivisions: 139, // dedication, etymology, extracts, 135 chapters, epilogue
  },
];
