import type { WorkConfig } from "./model.ts";

export const works: WorkConfig[] = [
  {
    slug: "the-iliad",
    author: "homer",
    authorName: "Homer",
    title: "The Iliad",
    composedYear: -750,
    era: "archaic-greece",
    adapter: "pg-the-iliad",
    rawDir: "raw/pg/the-iliad",
    translator: "Samuel Butler",
    refScheme: { primary: "book.paragraph", aliases: [], lineation: null },
  },
  {
    slug: "the-frogs",
    author: "aristophanes",
    authorName: "Aristophanes",
    title: "The Frogs",
    composedYear: -405,
    era: "classical-greece",
    adapter: "pg-the-frogs",
    rawDir: "raw/pg/the-frogs",
    translator: "Benjamin Bickley Rogers",
    refScheme: { primary: "line", aliases: [], lineation: "translation" },
  },
  {
    slug: "the-divine-comedy",
    author: "dante-alighieri",
    authorName: "Dante Alighieri",
    title: "The Divine Comedy",
    composedYear: 1320,
    era: "medieval",
    adapter: "se-divine-comedy",
    rawDir: "raw/se/the-divine-comedy",
    translator: "Henry Wadsworth Longfellow",
    refScheme: { primary: "cantica.canto:line", aliases: [], lineation: "translation" },
  },
  {
    slug: "histories",
    author: "herodotus",
    authorName: "Herodotus",
    title: "Histories",
    composedYear: -430,
    era: "classical-greece",
    adapter: "se-prose",
    rawDir: "raw/se/histories",
    translator: "G. C. Macaulay",
    refScheme: { primary: "book.paragraph", aliases: [], lineation: null },
    expectDivisions: 10, // translator's preface + 9 books
  },
  {
    slug: "history-of-the-peloponnesian-war",
    author: "thucydides",
    authorName: "Thucydides",
    title: "History of the Peloponnesian War",
    composedYear: -400,
    era: "classical-greece",
    adapter: "se-prose",
    rawDir: "raw/se/history-of-the-peloponnesian-war",
    translator: "Richard Crawley",
    refScheme: { primary: "chapter.paragraph", aliases: [], lineation: null },
    skipFiles: ["plans.xhtml"], // battle-plan images: no image path in v1
    expectDivisions: 27, // dedication + 26 chapters
  },
  {
    slug: "meditations",
    author: "marcus-aurelius",
    authorName: "Marcus Aurelius",
    title: "Meditations",
    composedYear: 175,
    era: "imperial-rome",
    adapter: "se-prose",
    rawDir: "raw/se/meditations",
    translator: "George Long",
    refScheme: { primary: "book.paragraph", aliases: [], lineation: null },
    expectDivisions: 12,
  },
  {
    slug: "the-prince",
    author: "niccolo-machiavelli",
    authorName: "Niccolò Machiavelli",
    title: "The Prince",
    composedYear: 1513,
    era: "renaissance",
    adapter: "se-prose",
    rawDir: "raw/se/the-prince",
    translator: "W. K. Marriott",
    refScheme: { primary: "chapter.paragraph", aliases: [], lineation: null },
    expectDivisions: 29, // intro, biography, dedication, 26 chapters
  },
  {
    slug: "leviathan",
    author: "thomas-hobbes",
    authorName: "Thomas Hobbes",
    title: "Leviathan",
    composedYear: 1651,
    era: "early-modern",
    adapter: "se-prose",
    rawDir: "raw/se/leviathan",
    translator: null,
    refScheme: { primary: "chapter.paragraph", aliases: [], lineation: null },
    expectDivisions: 50, // dedication, introduction, 47 chapters, conclusion
  },
  {
    slug: "moby-dick",
    author: "herman-melville",
    authorName: "Herman Melville",
    title: "Moby-Dick",
    composedYear: 1851,
    era: "nineteenth-century",
    adapter: "se-prose",
    rawDir: "raw/se/moby-dick",
    translator: null,
    refScheme: { primary: "chapter.paragraph", aliases: [], lineation: null },
    expectDivisions: 139, // dedication, etymology, extracts, 135 chapters, epilogue
  },
  {
    slug: "discourses",
    author: "epictetus",
    authorName: "Epictetus",
    title: "Discourses",
    composedYear: 108,
    era: "imperial-rome",
    adapter: "se-prose",
    rawDir: "raw/se/discourses",
    translator: "George Long",
    refScheme: { primary: "book.chapter.paragraph", aliases: [], lineation: null },
  },
  {
    slug: "the-city-of-god",
    author: "augustine-of-hippo",
    authorName: "Augustine of Hippo",
    title: "The City of God",
    composedYear: 426,
    era: "late-antiquity",
    adapter: "se-prose",
    rawDir: "raw/se/the-city-of-god",
    translator: "Marcus Dods et al.",
    refScheme: { primary: "book.chapter.paragraph", aliases: [], lineation: null },
  },
  {
    slug: "don-quixote",
    author: "miguel-de-cervantes-saavedra",
    authorName: "Miguel de Cervantes Saavedra",
    title: "Don Quixote",
    composedYear: 1615,
    era: "renaissance",
    adapter: "se-prose",
    rawDir: "raw/se/don-quixote",
    translator: "John Ormsby",
    refScheme: { primary: "chapter.paragraph", aliases: [], lineation: null },
  },
  {
    slug: "gullivers-travels",
    author: "jonathan-swift",
    authorName: "Jonathan Swift",
    title: "Gulliver's Travels",
    composedYear: 1726,
    era: "eighteenth-century",
    adapter: "se-prose",
    rawDir: "raw/se/gullivers-travels",
    translator: null,
    refScheme: { primary: "part.chapter.paragraph", aliases: [], lineation: null },
  },
  {
    slug: "the-wealth-of-nations",
    author: "adam-smith",
    authorName: "Adam Smith",
    title: "The Wealth of Nations",
    composedYear: 1776,
    era: "eighteenth-century",
    adapter: "se-prose",
    rawDir: "raw/se/the-wealth-of-nations",
    translator: null,
    refScheme: { primary: "book.chapter.paragraph", aliases: [], lineation: null },
  },
  {
    slug: "the-federalist-papers",
    author: "alexander-hamilton",
    authorName: "Hamilton, Madison, and Jay",
    title: "The Federalist Papers",
    composedYear: 1788,
    era: "eighteenth-century",
    adapter: "se-prose",
    rawDir: "raw/se/the-federalist-papers",
    translator: null,
    refScheme: { primary: "paper.paragraph", aliases: [], lineation: null },
  },
  {
    slug: "decline-and-fall",
    author: "edward-gibbon",
    authorName: "Edward Gibbon",
    title: "The History of the Decline and Fall of the Roman Empire",
    composedYear: 1789,
    era: "eighteenth-century",
    adapter: "se-prose",
    rawDir: "raw/se/decline-and-fall",
    translator: null,
    refScheme: { primary: "chapter.paragraph", aliases: [], lineation: null },
    skipFiles: ["appendix.xhtml"], // maps only; no image path in v1
  },
  {
    slug: "on-liberty",
    author: "john-stuart-mill",
    authorName: "John Stuart Mill",
    title: "On Liberty",
    composedYear: 1859,
    era: "nineteenth-century",
    adapter: "se-prose",
    rawDir: "raw/se/on-liberty",
    translator: null,
    refScheme: { primary: "chapter.paragraph", aliases: [], lineation: null },
  },
  {
    slug: "war-and-peace",
    author: "leo-tolstoy",
    authorName: "Leo Tolstoy",
    title: "War and Peace",
    composedYear: 1869,
    era: "nineteenth-century",
    adapter: "se-prose",
    rawDir: "raw/se/war-and-peace",
    translator: "Louise and Aylmer Maude",
    refScheme: { primary: "book.chapter.paragraph", aliases: [], lineation: null },
  },
  {
    slug: "the-brothers-karamazov",
    author: "fyodor-dostoevsky",
    authorName: "Fyodor Dostoevsky",
    title: "The Brothers Karamazov",
    composedYear: 1880,
    era: "nineteenth-century",
    adapter: "se-prose",
    rawDir: "raw/se/the-brothers-karamazov",
    translator: "Constance Garnett",
    refScheme: { primary: "part.book.chapter.paragraph", aliases: [], lineation: null },
  },
];
