import type { WorkConfig } from "./model.ts";

export const works: WorkConfig[] = [
  {
    slug: "the-iliad",
    author: "homer",
    authorName: "Homer",
    title: "The Iliad",
    composedYear: -750,
    era: "archaic-greece",
    adapter: "pg-the-iliad",
    rawDir: "raw/pg/the-iliad",
    translator: "Samuel Butler",
    refScheme: { primary: "book.paragraph", aliases: [], lineation: null },
  },
  {
    slug: "the-frogs",
    author: "aristophanes",
    authorName: "Aristophanes",
    title: "The Frogs",
    composedYear: -405,
    era: "classical-greece",
    adapter: "pg-the-frogs",
    rawDir: "raw/pg/the-frogs",
    translator: "Benjamin Bickley Rogers",
    refScheme: { primary: "line", aliases: [], lineation: "translation" },
  },
  {
    slug: "the-divine-comedy",
    author: "dante-alighieri",
    authorName: "Dante Alighieri",
    title: "The Divine Comedy",
    composedYear: 1320,
    era: "medieval",
    adapter: "se-divine-comedy",
    rawDir: "raw/se/the-divine-comedy",
    translator: "Henry Wadsworth Longfellow",
    refScheme: { primary: "cantica.canto:line", aliases: [], lineation: "translation" },
  },
  {
    slug: "histories",
    author: "herodotus",
    authorName: "Herodotus",
    title: "Histories",
    composedYear: -430,
    era: "classical-greece",
    adapter: "se-prose",
    rawDir: "raw/se/histories",
    translator: "G. C. Macaulay",
    refScheme: { primary: "book.paragraph", aliases: [], lineation: null },
    expectDivisions: 10, // translator's preface + 9 books
  },
  {
    slug: "history-of-the-peloponnesian-war",
    author: "thucydides",
    authorName: "Thucydides",
    title: "History of the Peloponnesian War",
    composedYear: -400,
    era: "classical-greece",
    adapter: "se-prose",
    rawDir: "raw/se/history-of-the-peloponnesian-war",
    translator: "Richard Crawley",
    refScheme: { primary: "chapter.paragraph", aliases: [], lineation: null },
    skipFiles: ["plans.xhtml"], // battle-plan images: no image path in v1
    expectDivisions: 27, // dedication + 26 chapters
  },
  {
    slug: "meditations",
    author: "marcus-aurelius",
    authorName: "Marcus Aurelius",
    title: "Meditations",
    composedYear: 175,
    era: "imperial-rome",
    adapter: "se-prose",
    rawDir: "raw/se/meditations",
    translator: "George Long",
    refScheme: { primary: "book.paragraph", aliases: [], lineation: null },
    expectDivisions: 12,
  },
  {
    slug: "the-prince",
    author: "niccolo-machiavelli",
    authorName: "Niccolò Machiavelli",
    title: "The Prince",
    composedYear: 1513,
    era: "renaissance",
    adapter: "se-prose",
    rawDir: "raw/se/the-prince",
    translator: "W. K. Marriott",
    refScheme: { primary: "chapter.paragraph", aliases: [], lineation: null },
    expectDivisions: 29, // intro, biography, dedication, 26 chapters
  },
  {
    slug: "leviathan",
    author: "thomas-hobbes",
    authorName: "Thomas Hobbes",
    title: "Leviathan",
    composedYear: 1651,
    era: "early-modern",
    adapter: "se-prose",
    rawDir: "raw/se/leviathan",
    translator: null,
    refScheme: { primary: "chapter.paragraph", aliases: [], lineation: null },
    expectDivisions: 50, // dedication, introduction, 47 chapters, conclusion
  },
  {
    slug: "moby-dick",
    author: "herman-melville",
    authorName: "Herman Melville",
    title: "Moby-Dick",
    composedYear: 1851,
    era: "nineteenth-century",
    adapter: "se-prose",
    rawDir: "raw/se/moby-dick",
    translator: null,
    refScheme: { primary: "chapter.paragraph", aliases: [], lineation: null },
    expectDivisions: 139, // dedication, etymology, extracts, 135 chapters, epilogue
  },
  {
    slug: "discourses",
    author: "epictetus",
    authorName: "Epictetus",
    title: "Discourses",
    composedYear: 108,
    era: "imperial-rome",
    adapter: "se-prose",
    rawDir: "raw/se/discourses",
    translator: "George Long",
    refScheme: { primary: "book.chapter.paragraph", aliases: [], lineation: null },
  },
  {
    slug: "the-city-of-god",
    author: "augustine-of-hippo",
    authorName: "Augustine of Hippo",
    title: "The City of God",
    composedYear: 426,
    era: "late-antiquity",
    adapter: "se-prose",
    rawDir: "raw/se/the-city-of-god",
    translator: "Marcus Dods et al.",
    refScheme: { primary: "book.chapter.paragraph", aliases: [], lineation: null },
  },
  {
    slug: "don-quixote",
    author: "miguel-de-cervantes-saavedra",
    authorName: "Miguel de Cervantes Saavedra",
    title: "Don Quixote",
    composedYear: 1615,
    era: "renaissance",
    adapter: "se-prose",
    rawDir: "raw/se/don-quixote",
    translator: "John Ormsby",
    refScheme: { primary: "chapter.paragraph", aliases: [], lineation: null },
  },
  {
    slug: "gullivers-travels",
    author: "jonathan-swift",
    authorName: "Jonathan Swift",
    title: "Gulliver's Travels",
    composedYear: 1726,
    era: "eighteenth-century",
    adapter: "se-prose",
    rawDir: "raw/se/gullivers-travels",
    translator: null,
    refScheme: { primary: "part.chapter.paragraph", aliases: [], lineation: null },
  },
  {
    slug: "the-wealth-of-nations",
    author: "adam-smith",
    authorName: "Adam Smith",
    title: "The Wealth of Nations",
    composedYear: 1776,
    era: "eighteenth-century",
    adapter: "se-prose",
    rawDir: "raw/se/the-wealth-of-nations",
    translator: null,
    refScheme: { primary: "book.chapter.paragraph", aliases: [], lineation: null },
  },
  {
    slug: "the-federalist-papers",
    author: "alexander-hamilton",
    authorName: "Hamilton, Madison, and Jay",
    title: "The Federalist Papers",
    composedYear: 1788,
    era: "eighteenth-century",
    adapter: "se-prose",
    rawDir: "raw/se/the-federalist-papers",
    translator: null,
    refScheme: { primary: "paper.paragraph", aliases: [], lineation: null },
  },
  {
    slug: "decline-and-fall",
    author: "edward-gibbon",
    authorName: "Edward Gibbon",
    title: "The History of the Decline and Fall of the Roman Empire",
    composedYear: 1789,
    era: "eighteenth-century",
    adapter: "se-prose",
    rawDir: "raw/se/decline-and-fall",
    translator: null,
    refScheme: { primary: "chapter.paragraph", aliases: [], lineation: null },
    skipFiles: ["appendix.xhtml"], // maps only; no image path in v1
  },
  {
    slug: "on-liberty",
    author: "john-stuart-mill",
    authorName: "John Stuart Mill",
    title: "On Liberty",
    composedYear: 1859,
    era: "nineteenth-century",
    adapter: "se-prose",
    rawDir: "raw/se/on-liberty",
    translator: null,
    refScheme: { primary: "chapter.paragraph", aliases: [], lineation: null },
  },
  {
    slug: "war-and-peace",
    author: "leo-tolstoy",
    authorName: "Leo Tolstoy",
    title: "War and Peace",
    composedYear: 1869,
    era: "nineteenth-century",
    adapter: "se-prose",
    rawDir: "raw/se/war-and-peace",
    translator: "Louise and Aylmer Maude",
    refScheme: { primary: "book.chapter.paragraph", aliases: [], lineation: null },
  },
  {
    slug: "the-brothers-karamazov",
    author: "fyodor-dostoevsky",
    authorName: "Fyodor Dostoevsky",
    title: "The Brothers Karamazov",
    composedYear: 1880,
    era: "nineteenth-century",
    adapter: "se-prose",
    rawDir: "raw/se/the-brothers-karamazov",
    translator: "Constance Garnett",
    refScheme: { primary: "part.book.chapter.paragraph", aliases: [], lineation: null },
  },
  {
    slug: "the-two-gentlemen-of-verona",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "The Two Gentlemen of Verona",
    composedYear: 1590,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/the-two-gentlemen-of-verona",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "the-taming-of-the-shrew",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "The Taming of the Shrew",
    composedYear: 1591,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/the-taming-of-the-shrew",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "henry-vi-part-ii",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "Henry VI, Part II",
    composedYear: 1591,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/henry-vi-part-ii",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "henry-vi-part-iii",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "Henry VI, Part III",
    composedYear: 1591,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/henry-vi-part-iii",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "henry-vi-part-i",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "Henry VI, Part I",
    composedYear: 1592,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/henry-vi-part-i",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "titus-andronicus",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "Titus Andronicus",
    composedYear: 1592,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/titus-andronicus",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "richard-iii",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "Richard III",
    composedYear: 1593,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/richard-iii",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "edward-iii",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "Edward III",
    composedYear: 1593,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/edward-iii",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "the-comedy-of-errors",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "The Comedy of Errors",
    composedYear: 1594,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/the-comedy-of-errors",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "loves-labours-lost",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "Love's Labour's Lost",
    composedYear: 1595,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/loves-labours-lost",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "richard-ii",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "Richard II",
    composedYear: 1595,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/richard-ii",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "romeo-and-juliet",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "Romeo and Juliet",
    composedYear: 1595,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/romeo-and-juliet",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "a-midsummer-nights-dream",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "A Midsummer Night's Dream",
    composedYear: 1595,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/a-midsummer-nights-dream",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "king-john",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "King John",
    composedYear: 1596,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/king-john",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "the-merchant-of-venice",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "The Merchant of Venice",
    composedYear: 1596,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/the-merchant-of-venice",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "henry-iv-part-i",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "Henry IV, Part I",
    composedYear: 1597,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/henry-iv-part-i",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "the-merry-wives-of-windsor",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "The Merry Wives of Windsor",
    composedYear: 1597,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/the-merry-wives-of-windsor",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "henry-iv-part-ii",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "Henry IV, Part II",
    composedYear: 1598,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/henry-iv-part-ii",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "much-ado-about-nothing",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "Much Ado About Nothing",
    composedYear: 1598,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/much-ado-about-nothing",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "henry-v",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "Henry V",
    composedYear: 1599,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/henry-v",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "julius-caesar",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "Julius Caesar",
    composedYear: 1599,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/julius-caesar",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "as-you-like-it",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "As You Like It",
    composedYear: 1599,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/as-you-like-it",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "hamlet",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "Hamlet",
    composedYear: 1601,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/hamlet",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "twelfth-night",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "Twelfth Night",
    composedYear: 1601,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/twelfth-night",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "troilus-and-cressida",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "Troilus and Cressida",
    composedYear: 1602,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/troilus-and-cressida",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "measure-for-measure",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "Measure for Measure",
    composedYear: 1604,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/measure-for-measure",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "othello",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "Othello",
    composedYear: 1604,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/othello",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "alls-well-that-ends-well",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "All's Well That Ends Well",
    composedYear: 1605,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/alls-well-that-ends-well",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "king-lear",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "King Lear",
    composedYear: 1605,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/king-lear",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "macbeth",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "Macbeth",
    composedYear: 1606,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/macbeth",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "antony-and-cleopatra",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "Antony and Cleopatra",
    composedYear: 1606,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/antony-and-cleopatra",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "coriolanus",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "Coriolanus",
    composedYear: 1608,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/coriolanus",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "timon-of-athens",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "Timon of Athens",
    composedYear: 1608,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/timon-of-athens",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "pericles",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "Pericles",
    composedYear: 1608,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/pericles",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "cymbeline",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "Cymbeline",
    composedYear: 1610,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/cymbeline",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "the-winters-tale",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "The Winter's Tale",
    composedYear: 1611,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/the-winters-tale",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "the-tempest",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "The Tempest",
    composedYear: 1611,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/the-tempest",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "henry-viii",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "Henry VIII",
    composedYear: 1613,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/henry-viii",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
  {
    slug: "the-two-noble-kinsmen",
    author: "william-shakespeare",
    authorName: "William Shakespeare",
    title: "The Two Noble Kinsmen",
    composedYear: 1613,
    era: "renaissance",
    adapter: "se-drama",
    rawDir: "raw/se/the-two-noble-kinsmen",
    translator: null,
    refScheme: { primary: "act.scene:line", aliases: [], lineation: "edition" },
  },
];
